version: "3.8"
services:
  api:
    build: ./todo-api
    container_name: todo-api
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/todos
    depends_on:
      - mongo
    volumes:
      - ./todo-api:/app
      - /app/node_modules

  mongo:
    image: mongo:6
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
