---
- name: Installer les dépendances
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
    update_cache: yes

- name: Ajouter la clé GPG Docker
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: Ajouter le dépôt Docker
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable
    state: present

- name: Installer Docker
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
    update_cache: yes

- name: Installer pip (utile si besoin Python)
  apt:
    name: python3-pip
    state: present

- name: Installer Docker Compose V2 (binaire officiel)
  get_url:
    url: https://github.com/docker/compose/releases/download/v2.27.0/docker-compose-linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: '0755'

- name: Ajouter l'utilisateur au groupe docker
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes

- name: Démarrer et activer le service Docker
  service:
    name: docker
    state: started
    enabled: yes
